# Generated by Django 2.2.6 on 2019-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('image', models.ImageField(default='NULL', upload_to='images/')),
                ('text', models.CharField(default='NULL', max_length=150)),
                ('time', models.TimeField()),
            ],
        ),
    ]
